In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
# Using TensorFlow backend.

Using TensorFlow backend.


In [2]:
combination = {30:[20,50,75],50:[20,50,75],80:[20,50,75]}

In [3]:
df = pd.read_csv('GoogleStocks.csv')
df = df.drop(df.index[0])
# print(df)
avg = []
for index,row in df.iterrows():
#     print(row)
    temp = float(row['low']) + float(row['high'])
#     print(temp)
    temp = temp/2
    avg.append(temp)

df['avg'] = avg
# df
df = df[['avg','volume']]

In [4]:
def predict(time_steps,regressor):
    
    X_test = []
    for i in range(0, 55):
        X_test.append(training_set_scaled[i-time_steps+690:i+690, 0:2])
    X_test = np.array(X_test)
    X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 2))
    predicted_stock_price = regressor.predict(X_test)
    # print(predicted_stock_price)
    predicted_stock_price = sc.inverse_transform(predicted_stock_price)
    print(predicted_stock_price)

In [5]:
df.isna().any()

# print(df)
sc = MinMaxScaler(feature_range = (0,2))
training_set_scaled = sc.fit_transform(df)

/home/vatsal/.local/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype float64, object were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [6]:
for k in combination.keys():
    steps = combination[k]
    for st in steps:
        print("**********************************************************")
        print(k,st)
        X_train = []
        y_train = []
        for i in range(st, 690):
            X_train.append(training_set_scaled[i-st:i, 0:2])
            y_train.append(training_set_scaled[i, 0:2])

        X_train, y_train = np.array(X_train), np.array(y_train)
        # print(X_train)

        X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 2))
        # X_train


        regressor = Sequential()

        regressor.add(LSTM(units = k, return_sequences = True, input_shape = (X_train.shape[1], 2)))
        regressor.add(Dropout(0.2))

        regressor.add(LSTM(units = k, return_sequences = True))
        regressor.add(Dropout(0.2))

        regressor.add(LSTM(units = k, return_sequences = True))
        regressor.add(Dropout(0.2))

        regressor.add(LSTM(units = k))
        regressor.add(Dropout(0.2))

        regressor.add(Dense(units = 2))

        regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

        regressor.fit(X_train, y_train, epochs = 20, batch_size = 32)
        predict(st,regressor)

**********************************************************
30 20
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Epoch 1/20
670/670 [==============================] - 5s 8ms/step - loss: 0.3201
Epoch 2/20
670/670 [==============================] - 1s 2ms/step - loss: 0.0884
Epoch 3/20
670/670 [==============================] - 1s 2ms/step - loss: 0.0628
Epoch 4/20
670/670 [==============================] - 1s 2ms/step - loss: 0.0580
Epoch 5/20
670/670 [==============================] - 1s 2ms/step - loss: 0.0543
Epoch 6/20
670/670 [==============================] - 1s 2ms/step - loss: 0.0515
Epoch 7/20
670/670 [==============================] - 1s 2ms/step - loss: 0.0528
Epoch 8/20
670/670 [==============================] - 1s 2ms/step - loss: 0.0561
Epoch 9/20
670/670 [==============================] 

615/615 [==============================] - 5s 8ms/step - loss: 0.0567
Epoch 7/20
615/615 [==============================] - 4s 6ms/step - loss: 0.0539
Epoch 8/20
615/615 [==============================] - 5s 8ms/step - loss: 0.0567
Epoch 9/20
615/615 [==============================] - 4s 6ms/step - loss: 0.0550
Epoch 10/20
615/615 [==============================] - 4s 6ms/step - loss: 0.0510
Epoch 11/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0539
Epoch 12/20
615/615 [==============================] - 5s 9ms/step - loss: 0.0573
Epoch 13/20
615/615 [==============================] - 5s 8ms/step - loss: 0.0542
Epoch 14/20
615/615 [==============================] - 5s 9ms/step - loss: 0.0515
Epoch 15/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0502
Epoch 16/20
615/615 [==============================] - 4s 6ms/step - loss: 0.0513
Epoch 17/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0522
Epoch 18/20
615/615 [==========

Epoch 1/20
615/615 [==============================] - 11s 17ms/step - loss: 0.2420
Epoch 2/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0666
Epoch 3/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0557
Epoch 4/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0550
Epoch 5/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0519
Epoch 6/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0503
Epoch 7/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0514
Epoch 8/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0489
Epoch 9/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0478
Epoch 10/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0487
Epoch 11/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0474
Epoch 12/20
615/615 [==============================] - 4s 7ms/step - loss: 0.0476
Epoch 13/20
615/615 [==

Epoch 18/20
640/640 [==============================] - 4s 6ms/step - loss: 0.0441
Epoch 19/20
640/640 [==============================] - 4s 6ms/step - loss: 0.0445
Epoch 20/20
640/640 [==============================] - 4s 6ms/step - loss: 0.0418
[[6.9566058e+02 1.4175376e+06]
 [6.9351648e+02 1.4199890e+06]
 [6.9237347e+02 1.4297094e+06]
 [6.9212378e+02 1.4453222e+06]
 [6.9217310e+02 1.4627299e+06]
 [6.9207648e+02 1.4787058e+06]
 [6.9177179e+02 1.4922122e+06]
 [6.9172498e+02 1.5052752e+06]
 [6.9201575e+02 1.5176560e+06]
 [6.9245172e+02 1.5275632e+06]
 [6.9286493e+02 1.5337132e+06]
 [6.9318060e+02 1.5355080e+06]
 [6.9339526e+02 1.5329631e+06]
 [6.9353101e+02 1.5262426e+06]
 [6.9378864e+02 1.5168025e+06]
 [6.9424188e+02 1.5058019e+06]
 [6.9495801e+02 1.4945384e+06]
 [6.9590057e+02 1.4834980e+06]
 [6.9705908e+02 1.4730848e+06]
 [6.9842749e+02 1.4634480e+06]
 [7.0023444e+02 1.4560505e+06]
 [7.0254492e+02 1.4518456e+06]
 [7.0514001e+02 1.4505465e+06]
 [7.0775061e+02 1.4515314e+06]
 [7.101613

In [7]:
for k in combination.keys():
    steps = combination[k]
    for st in steps:
        print("*************************************************************")
        print(k,st)
        X_train = []
        y_train = []
        for i in range(st, 690):
            X_train.append(training_set_scaled[i-st:i, 0:2])
            y_train.append(training_set_scaled[i, 0:2])

        X_train, y_train = np.array(X_train), np.array(y_train)
        # print(X_train)

        X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 2))
        # X_train


        regressor = Sequential()

        regressor.add(LSTM(units = k, return_sequences = True, input_shape = (X_train.shape[1], 2)))
        regressor.add(Dropout(0.2))

        regressor.add(LSTM(units = k, return_sequences = True))
        regressor.add(Dropout(0.2))

        regressor.add(LSTM(units = k))
        regressor.add(Dropout(0.2))

        regressor.add(Dense(units = 2))

        regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

        regressor.fit(X_train, y_train, epochs = 20, batch_size = 32)
        predict(st,regressor)

*************************************************************
30 20
Epoch 1/20
670/670 [==============================] - 9s 13ms/step - loss: 0.2551
Epoch 2/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0831
Epoch 3/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0613
Epoch 4/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0595
Epoch 5/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0573
Epoch 6/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0503
Epoch 7/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0489
Epoch 8/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0501
Epoch 9/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0511
Epoch 10/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0498
Epoch 11/20
670/670 [==============================] - 1s 1ms/step - loss: 0.0491
Epoch 12/20
670/670 [=================

615/615 [==============================] - 3s 5ms/step - loss: 0.0481
Epoch 18/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0469
Epoch 19/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0463
Epoch 20/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0453
[[7.1547681e+02 1.3762548e+06]
 [7.1349518e+02 1.3861996e+06]
 [7.1243530e+02 1.4099372e+06]
 [7.1214746e+02 1.4370608e+06]
 [7.1227466e+02 1.4582624e+06]
 [7.1259747e+02 1.4720920e+06]
 [7.1307196e+02 1.4818425e+06]
 [7.1398444e+02 1.4955165e+06]
 [7.1516565e+02 1.5084491e+06]
 [7.1644373e+02 1.5155879e+06]
 [7.1767780e+02 1.5163365e+06]
 [7.1877466e+02 1.5113279e+06]
 [7.1966864e+02 1.5017091e+06]
 [7.2034119e+02 1.4879471e+06]
 [7.2091840e+02 1.4739884e+06]
 [7.2135089e+02 1.4602875e+06]
 [7.2169940e+02 1.4483740e+06]
 [7.2199847e+02 1.4372280e+06]
 [7.2234247e+02 1.4271718e+06]
 [7.2281195e+02 1.4179759e+06]
 [7.2363702e+02 1.4136912e+06]
 [7.2477667e+02 1.4141501e+06]
 [

Epoch 1/20
615/615 [==============================] - 14s 23ms/step - loss: 0.2503
Epoch 2/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0731
Epoch 3/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0561
Epoch 4/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0488
Epoch 5/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0483
Epoch 6/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0460
Epoch 7/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0435
Epoch 8/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0479
Epoch 9/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0484
Epoch 10/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0418
Epoch 11/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0436
Epoch 12/20
615/615 [==============================] - 3s 5ms/step - loss: 0.0439
Epoch 13/20
615/615 [==

640/640 [==============================] - 3s 4ms/step - loss: 0.0411
Epoch 18/20
640/640 [==============================] - 3s 4ms/step - loss: 0.0399
Epoch 19/20
640/640 [==============================] - 3s 4ms/step - loss: 0.0391
Epoch 20/20
640/640 [==============================] - 3s 4ms/step - loss: 0.0391
[[6.9578381e+02 1.4147550e+06]
 [6.9529761e+02 1.4505475e+06]
 [6.9769171e+02 1.5228960e+06]
 [7.0008160e+02 1.5877665e+06]
 [7.0056152e+02 1.6190632e+06]
 [6.9948010e+02 1.6230725e+06]
 [6.9808960e+02 1.6179928e+06]
 [6.9846198e+02 1.6315740e+06]
 [6.9917938e+02 1.6424385e+06]
 [6.9921899e+02 1.6349734e+06]
 [6.9869525e+02 1.6125722e+06]
 [6.9788629e+02 1.5804554e+06]
 [6.9704803e+02 1.5437046e+06]
 [6.9624713e+02 1.5034235e+06]
 [6.9627820e+02 1.4720200e+06]
 [6.9682904e+02 1.4477089e+06]
 [6.9797083e+02 1.4329609e+06]
 [6.9927112e+02 1.4212482e+06]
 [7.0077283e+02 1.4125365e+06]
 [7.0242792e+02 1.4050198e+06]
 [7.0518854e+02 1.4117640e+06]
 [7.0864331e+02 1.4292162e+06]
 [